sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 195277
  alioss:
    access-key-id: LTAI5t7PNgVXGv2r8eiVr1Kg
    access-key-secret: zp983E4tfxszDVBKwqIGtd25FZ9jfc
    bucket-name: sky526-take-out--1
    endpoint: oss-cn-hangzhou.aliyuncs.com
  redis:
    port: 6379
    host: localhost
    password: 195277
    database: 10
  wechat:
    appid: wx171ed41bb228c98b
    secret: 74a86f5efad0572bad4e5e975bc58788